name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Python-lint-annotate: maintain code quality with annotated PRs and pushes
      # You may pin to the exact commit or the version.
      # uses: marian-code/python-lint-annotate@33c09aad023fd055523fe55a766b3d0b36eeffa6
      uses: marian-code/python-lint-annotate@v3
      with:
        # A list of all paths to test
        python-root-list: # optional, default is .
        # Use Pylint
        use-pylint: # optional, default is true
        # Use pycodestyle
        use-pycodestyle: # optional, default is true
        # Use Flake8
        use-flake8: # optional, default is true
        # Use Black
        use-black: # optional, default is true
        # Use mypy
        use-mypy: # optional, default is true
        # Use isort
        use-isort: # optional, default is true
        # Use vulture
        use-vulture: # optional, default is true
        # Use pydocstyle
        use-pydocstyle: # optional, default is true
        # Extra options: pylint $(extra-pylint-options) $(python-root-list)
        extra-pylint-options: # optional, default is 
        # Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)
        extra-pycodestyle-options: # optional, default is 
        # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
        extra-flake8-options: # optional, default is 
        # Extra options: black --check $(extra-black-options) $(python-root-list)
        extra-black-options: # optional, default is 
        # Extra options: mypy $(extra-mypy-options) $(python-root-list)
        extra-mypy-options: # optional, default is 
        # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff 
        extra-isort-options: # optional, default is 
        # Extra options: vulture $(extra-vulture-options) $(python-root-list)
        extra-vulture-options: # optional, default is 
        # Extra options: pydocstyle $(extra-pydocstyle-options) $(python-root-list)
        extra-pydocstyle-options: # optional, default is 
        # Set desired python version with this keyword
        python-version: # optional, default is 3.8
